projects:
  app:
    schemaPath: "src/schema.js"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma:
    schemaPath: "src/generated/prisma-schema.js"
    extensions:
      prisma: prisma.yml
