projects:
  app:
    schemaPath: 'src/lambda/bundle/schema.ts'
    extensions:
      endpoints:
        default: 'http://localhost:9000/graphql'
  prisma:
    schemaPath: 'src/lambda/bundle/generated/prisma-schema.ts'
    extensions:
      prisma: prisma.yml
