// import SendGrid, { MailService, MailDataRequired } from '@sendgrid/mail';

import * as nodemailer from 'nodemailer';

// SendGrid.setApiKey(process.env.SENDGRID_API_KEY || '');

interface EmailData {
  to: String;
  from: String;
  subject: String;
  text: String;
  html: String;
}

// interface Email extends EmailData {}

export const sendTransactionalEmail = async (emailData: EmailData) => {
  // const mailSettings = {};

  // if (process.env.NODE_ENV === 'production') {
  // This will send the email in sandbox mode
  // mailSettings.mail_settings = {
  //   sandbox_mode: {
  //     enable: true,
  //   },
  // };

  // const data: MailDataRequired = {
  //   ...emailData,
  //   // ...mailSettings,
  // };

  // return SendGrid.send(emailData);
  // } else {
  const transport = nodemailer.createTransport({
    host: 'smtp.mailtrap.io',
    port: 2525,
    auth: {
      user: '00abda4abf8551', //generated by Mailtrap
      pass: '82046488050e87', //generated by Mailtrap
    },
  });

  const mailOptions: any = {
    from: 'no-reply@4-playersofcolorado.org',
    ...emailData,
  };

  return transport.sendMail(mailOptions, (error: any, info) => {
    if (error) {
      throw new Error(error);
    }

    const msg = 'Message sent';
    console.log(`${msg}: ${info.messageId}`);
    return Promise.resolve(msg);
  });
  // }

  // {
  //   to,
  //   from,
  //   subject,
  //   text,
  //   html,
  //   // templateId: 'd-f43daeeaef504760851f727007e0b5d0',
  //   // dynamic_template_data: {
  //   //   subject: 'Testing Templates',
  //   //   name: 'Some One',
  //   //   city: 'Denver',
  //   // },
  // },
};
